# Generated by Django 3.2.16 on 2022-11-03 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Packaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('film', models.CharField(max_length=50)),
                ('inner', models.CharField(max_length=50)),
                ('srp', models.CharField(default='No SRP', max_length=50)),
                ('outer', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('customer', models.CharField(max_length=50)),
                ('ppt', models.IntegerField()),
                ('pack_sz', models.IntegerField()),
                ('ppc', models.IntegerField()),
                ('packaging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packing.packaging')),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('start_date', models.DateField()),
                ('status', models.IntegerField(choices=[(0, 'Planning'), (1, 'Current'), (2, 'Complete')])),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('case_qty', models.IntegerField()),
                ('trays', models.IntegerField()),
                ('time', models.IntegerField()),
                ('complete', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packing.product')),
            ],
        ),
        migrations.CreateModel(
            name='Packing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.IntegerField(choices=[(1, 'Team 1'), (2, 'Team 2'), (3, 'Team 3'), (4, 'Team 4')])),
                ('day', models.IntegerField(choices=[(1, 'Saturday'), (2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday')])),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packing.run')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packing.week')),
            ],
        ),
    ]
