# Generated by Django 3.2.16 on 2022-11-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0002_alter_packing_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packing',
            name='day',
            field=models.CharField(choices=[('Saturday', 'Saturday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=15),
        ),
    ]
