# Generated by Django 3.2.16 on 2022-11-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0004_alter_run_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='run',
            name='time',
        ),
        migrations.RemoveField(
            model_name='run',
            name='trays',
        ),
        migrations.AddField(
            model_name='packing',
            name='complete',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packing',
            name='time',
            field=models.IntegerField(default=120),
            preserve_default=False,
        ),
    ]
