# Generated by Django 3.2.16 on 2022-11-04 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0005_auto_20221103_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packaging',
            name='film',
            field=models.CharField(help_text='Film used to seal an inner pack.', max_length=50),
        ),
        migrations.AlterField(
            model_name='packaging',
            name='inner',
            field=models.CharField(help_text='The inner packet.', max_length=50),
        ),
        migrations.AlterField(
            model_name='packaging',
            name='name',
            field=models.CharField(help_text='Name of the packing configuration.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='packaging',
            name='outer',
            field=models.CharField(help_text='The outer box or case in which inners are packed.', max_length=50),
        ),
        migrations.AlterField(
            model_name='packaging',
            name='srp',
            field=models.CharField(default='No SRP', help_text='Shelf Ready Pack, usually and extra 1-for-1 cover on the inner.', max_length=50),
        ),
        migrations.AlterField(
            model_name='packing',
            name='complete',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], max_length=50),
        ),
        migrations.AlterField(
            model_name='packing',
            name='day',
            field=models.CharField(choices=[('Saturday', 'Saturday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=50),
        ),
        migrations.AlterField(
            model_name='packing',
            name='time',
            field=models.IntegerField(help_text='Estimated time in minutes to complete the packing-run.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pack_sz',
            field=models.IntegerField(help_text='How many pieces fit in an inner packet.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='packaging',
            field=models.ForeignKey(help_text='Name of the packing configuration.', on_delete=django.db.models.deletion.CASCADE, to='packing.packaging'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ppc',
            field=models.IntegerField(help_text='Pieces Per Case'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ppt',
            field=models.IntegerField(help_text='Pieces(portions) Per Tray associated with a particular product.'),
        ),
        migrations.AlterField(
            model_name='run',
            name='case_qty',
            field=models.IntegerField(help_text='The number of cases that need to be packed to meet orders.'),
        ),
        migrations.AlterField(
            model_name='run',
            name='name',
            field=models.CharField(help_text='Product Name and case qty makes sense here.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='name',
            field=models.CharField(help_text='such as: October Wk2 2022, for the second week of october.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='start_date',
            field=models.DateField(help_text='Date the plan begins, usually a Saturday.'),
        ),
        migrations.AlterField(
            model_name='week',
            name='status',
            field=models.IntegerField(choices=[(0, 'Planning'), (1, 'Current'), (2, 'Complete')], help_text='Pre-production, production, post-production.'),
        ),
    ]
