# Generated by Django 3.2.16 on 2022-11-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0006_auto_20221104_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packing',
            name='day',
            field=models.IntegerField(choices=[(1, 'Saturday'), (2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday')]),
        ),
    ]
