# Generated by Django 3.2.16 on 2022-11-16 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0008_auto_20221116_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packing',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packing.teams'),
        ),
    ]
