# Generated by Django 3.2.16 on 2022-11-16 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0009_alter_packing_team'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teams',
            new_name='Team',
        ),
    ]
