# Generated by Django 3.2.16 on 2022-11-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0011_auto_20221116_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ppc',
            field=models.FloatField(help_text='Pieces Per Case'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ppt',
            field=models.FloatField(help_text='Pieces(portions) Per Tray associated with a particular product.'),
        ),
    ]
