# Generated by Django 3.2.16 on 2022-11-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0012_auto_20221118_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='start_date',
            field=models.DateField(help_text='Date the plan begins,Enter as YYYY-MM-DD.'),
        ),
    ]
