# Generated by Django 3.2.16 on 2022-11-25 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0014_auto_20221125_1413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='week',
            options={'ordering': ['-start_date'], 'permissions': [('can_edit_plan', 'Can edit a week plan'), ('can_create_plan', 'Can create a week plan'), ('can_delete_plan', 'Can delete a week plan')]},
        ),
    ]
