# Generated by Django 3.2.16 on 2022-11-25 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0015_alter_week_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pack',
            options={},
        ),
        migrations.AlterModelOptions(
            name='packingrun',
            options={'ordering': ['day']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='run',
            options={},
        ),
        migrations.AlterModelOptions(
            name='week',
            options={'ordering': ['-start_date']},
        ),
    ]
