# Generated by Django 3.2.16 on 2022-11-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0016_auto_20221125_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='name',
            field=models.CharField(help_text="Name, Customer and Case Qty - e.g. 'Charducks Trillionaire 230'", max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='name',
            field=models.CharField(help_text='such as: October 2022 Wk2, for the second week of october.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='status',
            field=models.IntegerField(choices=[(0, 'Planning'), (1, 'Current'), (2, 'Complete')], help_text='Planning(pre-packing), Current(in-progress), Complete(post-packing).'),
        ),
    ]
