# Generated by Django 3.2.16 on 2022-12-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0018_auto_20221130_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='packingrun',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
