# Generated by Django 3.2.16 on 2022-12-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0020_alter_packingrun_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packingrun',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional', null=True),
        ),
    ]
