# Generated by Django 3.2.16 on 2022-12-01 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0021_alter_packingrun_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packingrun',
            name='day',
            field=models.IntegerField(choices=[(1, 'Saturday'), (2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday')], help_text='Click Field To See Choices'),
        ),
        migrations.AlterField(
            model_name='packingrun',
            name='name',
            field=models.ForeignKey(help_text='Click Field To See Choices', on_delete=django.db.models.deletion.CASCADE, to='packing.run'),
        ),
        migrations.AlterField(
            model_name='packingrun',
            name='team',
            field=models.ForeignKey(help_text='Click Field To See Choices', on_delete=django.db.models.deletion.CASCADE, to='packing.team'),
        ),
        migrations.AlterField(
            model_name='packingrun',
            name='week',
            field=models.ForeignKey(help_text='Automatically Chooses Correct Plan Week', on_delete=django.db.models.deletion.CASCADE, to='packing.week'),
        ),
    ]
