# Generated by Django 3.2.16 on 2022-12-01 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('packing', '0022_auto_20221201_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='packingrun',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packingrun',
            name='created_when',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
