# Generated by Django 3.2.16 on 2022-12-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0023_auto_20221201_1647'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='week',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 1)), fields=('status',), name='unique_status'),
        ),
    ]
