# Generated by Django 3.2.16 on 2022-12-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0029_alter_week_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='status',
            field=models.IntegerField(choices=[(0, 'Planning'), (1, 'Complete'), (2, 'Delete'), (3, 'Current')], help_text="Set Status.  If This plan was created by mistake or is obsolete select 'Delete' for Admin to action."),
        ),
    ]
