# Generated by Django 3.2.16 on 2022-12-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0030_alter_week_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='current',
            field=models.BooleanField(default=False, help_text="Is this plan the current 'live' plan? "),
        ),
        migrations.AlterField(
            model_name='week',
            name='status',
            field=models.IntegerField(choices=[(0, 'Planning'), (1, 'Current'), (2, 'Complete'), (3, 'Delete')], help_text="Set Status.  If This plan was created by mistake or is obsolete select 'Delete' for Admin to action."),
        ),
    ]
