# Generated by Django 3.2.16 on 2022-12-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0031_auto_20221209_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='current',
        ),
        migrations.AlterField(
            model_name='packingrun',
            name='complete',
            field=models.CharField(choices=[('No', 'NO'), ('Yes', 'YES')], default='No', max_length=50),
        ),
    ]
