# Generated by Django 3.2.16 on 2022-12-12 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0032_auto_20221211_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='product',
            field=models.ForeignKey(help_text='Select a Product to add to this Run.', on_delete=django.db.models.deletion.CASCADE, to='packing.product'),
        ),
    ]
